---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: "IDCCO01"
  gather_facts: false
  connection: local
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     cisco.iosxr.iosxr_command:
       commands:
         - show running-config  

