---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: "ASRPrueba"
  gather_facts: false
  connection: local
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     cisco.iosxr.iosxr_command:
       commands:
         - show running-config  
     register: temp


   - name: print
     debug:
       msg: "{{ temp.meta }}"
